### ISSUE TITLE
Option for single slider

### ISSUE THREAD

**Issue by timothytqin** [D10S60948/react-native-range-slider-expo#1]
I know that there are already other single sliders out there, but I think it'd be nice if you had a prop that could turn your range slider into a single slider as well. I'm using it for distance and age, one which is a single slider, one which is a range slider and I'd like for the two to have similar styling. Thanks and great job on the component! Glad someone finally tackled the range slider for expo projects.

**Comment by avishain** [comment]
Was added to the to do list.
It should be simple as all logic is there so I assume it will be available in the next few days.
Thanks for the feedback.

**Comment by avishain** [comment]
Single slider was added.
Please note that it is not the default import so it should be "_import { Slider } from 'react-native-range-slider-expo'_;".
