### ISSUE TITLE
How should i reset the slider?

### ISSUE THREAD

**Issue by Cigan12** [D10S60948/react-native-range-slider-expo#10]
How i can reset the slider values and can I change its values directly?

**Comment by avishain** [comment]
See documentation. 
You have 2 props to set it:
"initialFromValue" & "initialToValue"

**Comment by LukasB-DEV** [comment]
Hello @D10S60948,

if I set initialFromValue and initialToValue the value changes. But is it also possible to set the knobs to the default position?

**Comment by avishain** [comment]
Hi,
I'm not sure i understand what you mean.
The knobs are positioned according to the initial values.

**Comment by LukasB-DEV** [comment]
Hi,

I have the following scenario: With the Range Slider an area is selected. If nothing is found in this area in the database, the slider should be set back to the starting position. If I understand correctly, initialFromValue and initialToValue are only taken into effect during the first render. However, I would like the slider to be on the very first starting position.

**Comment by avishain** [comment]
initialFromValue and initialToValue can be changed dynamically (on the fly).
It should look something like this:

```
     const [initialFromValue, setInitialFromValue] = useState(0);
     const [initialToValue, setInitialToValue] = useState(100);


     const resetSlider = () => {
          setInitialFromValue(0);
          setInitialToValue(100);
     }

    <RangeSlider
         ...
         initialFromValue={initialFromValue}
         initialToValue={initialToValue}
    />
```

**Comment by LukasB-DEV** [comment]
Thank you for your help! I found my problem. I had saved the value as sting.... accordingly initialFromValue and initialToValue could not do anything with it.
