### ISSUE TITLE
When using initialFromValue and IntitialToValue, the rendering appears to "jump" from the min/max to those values

### ISSUE THREAD

**Issue by abelfiore** [D10S60948/react-native-range-slider-expo#11]
I am using the initialFromValue and initialToValue to show the current setting, but when I re-render the component I am seeing a "jump" from the min/max values to the from/to values. Am I misusing the component in some way that would prevent this flickering from happening?

**Comment by avishain** [comment]
You are using it fine.
I didn't see this bug as initial values were a request I implemented but never used it myself.
I fixed it and will generate new version with the fix probably later on today.
Will let you know once version is out.

**Comment by avishain** [comment]
Should be fine now.
Please let me know if anything misbehaves.

**Comment by abelfiore** [comment]
Looks great thanks so much!
