### ISSUE TITLE
Call valueOnChange as its sliding

### ISSUE THREAD

**Issue by nguyenchr** [D10S60948/react-native-range-slider-expo#18]
Hey, great library here
I am currently using the single knob Slider and wondering if you think it would be hard to add functionality to call the `valueOnChange` handler as the gesture is happening, so my interface can update as a gesture is in progress

I'm looking into the code at the moment trying to work out how to implement it, but thought I would ask if you had any ideas while I was doing it

**Comment by avishain** [comment]
Hey
Look for rows 140-141.
If you'll add another prop (of type ref) you can set it the vaule on the fly.

**Comment by avishain** [comment]
HI again,
Not sure if you managed to handle it or not but I managed to do it but it complexes things and I want to keep the component as clean as possible.
If it will become increasing demand I will think of it but at the moment the implementation is ready but won't be merged.
