### ISSUE TITLE
Not working inside the modal on android

### ISSUE THREAD

**Issue by mawans** [D10S60948/react-native-range-slider-expo#19]
Hi, I am using the range slider inside the modal and its not drag able on android but on ios it works fine tell me what to do.

**Comment by avishain** [comment]
Hi,
I had the same problem. I didn't manage to solve it.
You can do one of the following: 
1- change the modal to be a screen (what I eventually did)
2- change the modal to be View with Stylesheet.absoluteFill 
3- use other range slider that does work inside a modal
