### ISSUE TITLE
Issue For Padding and height of slider bar

### ISSUE THREAD

**Issue by jazzy-pm** [D10S60948/react-native-range-slider-expo#22]
Can you give control on padding like on below section. I would like to define my own padding.

```
in RangeSlider.tsx  on Animated.View
<Animated.View style={[styles.container, { opacity, padding: styleSize === 'large' ? 7 : styleSize === 'medium' ? 14 : 5 }]}>
```

Also, add option of slider height to control the height using number
In below code the division value can be control if i define any number so it easy to control the height

```
in RangeSlider.tsx 
setBarHeight(sizeBasedOnStyleSize / 4)
```

**Comment by avishain** [comment]
Done. If still relevant update package to 1.4.2
