### ISSUE TITLE
App crashes on Android

### ISSUE THREAD

**Issue by FelipeBattistotti** [D10S60948/react-native-range-slider-expo#28]
Hello,
I install the package and occurs the following error:

Unable to resolve module react-native-svg from D:\FGB\git\tasktor-mobile\node_modules\react-native-range-slider-expo\src\Slider.tsx: react-native-svg could not be found within the project or in these directories:
  node_modules

![image](https://user-images.githubusercontent.com/61482397/186547439-39b167e1-6342-4eaf-bfd8-db00a9d86977.png)

**Comment by avishain** [comment]
you need to install 'react-native-svg'
in your CLI just run `expo install react-native-svg` (if you are not using expo then run `npm install react-native-svg && cd ios && pod install && cd ..`

**Comment by FelipeBattistotti** [comment]
@avishain 
This really solved it. Thanks a lot.
