### ISSUE TITLE
get broken on rtl app

### ISSUE THREAD

**Issue by AlonWiezer** [D10S60948/react-native-range-slider-expo#4]
hi,

This component looks great and excatly for my needs, but i notice it get messed up on RTL apps
![WhatsApp Image 2020-09-20 at 17 49 52](https://user-images.githubusercontent.com/67005557/93714195-ba107500-fb69-11ea-8daa-32d1bd90d9b8.jpeg)

added photo for example.
Thank you

**Comment by avishain** [comment]
Hi.
Fixed.
Try installing the new version.

**Comment by AlonWiezer** [comment]
working, Thank You!
