### ISSUE TITLE
Styling labels

### ISSUE THREAD

**Issue by melissafzhang** [D10S60948/react-native-range-slider-expo#6]
Hi,

Is there a way to style the labels? I want the labels to just sit on top of the knobs without the balloons. 

I'm also having an issue where the labels are not centered over the knobs.

<img width="251" alt="Screen Shot 2020-09-24 at 10 53 34 AM" src="https://user-images.githubusercontent.com/38673112/94175768-5ed5cf80-fe54-11ea-8db3-9930ed02a1c6.png">

Thanks!

**Comment by avishain** [comment]
Hi,

Thank you for raising this bug (of the labelnot centered over the knob). 
Was fixed in latest version (released couple of minutes ago).

About the labels styling - you can do => "valueLabelsBackgroundColor: 'transparent'" and then you'll get the labels without the balloon.
If you meant something else please add a small sketch.

**Comment by melissafzhang** [comment]
Thanks! Looking for something like this
<img width="244" alt="Screen Shot 2020-09-24 at 1 08 58 PM" src="https://user-images.githubusercontent.com/38673112/94188849-2c819d80-fe67-11ea-894a-ae9e1f0b2dc8.png">

**Comment by avishain** [comment]
I see. 
Set the label background color to 'transparent' and the text color to this purple and then to lower the labels you can easily create it by adjusting the code of the componen - look for the 'TextInput' components (rows no. around 240) and change the 'bottom' property of the style. Change it from 25 to 8 (or some other number. see the effect and change accordingly).

**Comment by jarink** [comment]
Hi, I am not able to make it like @melissafzhang stated.  I can't find the 'bottom' property now, i am using `^1.4.2` version.
Should i be doing something else in this version.

Just curious, Is it not possible to pass the styles in the `containerStyle` and make the label near the range bar?

Thank you

**Comment by jarink** [comment]
@avishain can we make any props for changing bottom and font size for the balloon, or pass any props for styles changes?
