### ISSUE TITLE
use in modal

### ISSUE THREAD

**Issue by rootmctoki** [D10S60948/react-native-range-slider-expo#7]
Hello.

When applied in <Modal>, there is a problem that touch and sliding are not possible. 

What should I do?

**Comment by avishain** [comment]
Hi,

I had the same problem.
The problem is that RN 'Modal' do not support 'PanGestureHandler' touches.

Since both RN components there is nothing can be done regarding this issue. 
I tried some work arounds with no success.

I ended up creating my own custom 'Modal'.
