### ISSUE TITLE
An error on expo latest version: Invarian Violation: No callback found with cbID 2 and callID 1 for module <unkown>. Args: ' [{"app_state": "active"}]'

### ISSUE THREAD

**Issue by Cigan12** [D10S60948/react-native-range-slider-expo#8]
This on Iphone XR, and on android another one: Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication), i registered module like in docs 
![image](https://user-images.githubusercontent.com/42859813/96576139-ee5b8a80-12fb-11eb-9751-e112de775f02.png)
![image](https://user-images.githubusercontent.com/42859813/96576167-fc111000-12fb-11eb-8e9e-d2d684e35166.png)

![image](https://user-images.githubusercontent.com/42859813/96576181-016e5a80-12fc-11eb-8e71-28ce2d0b5dd2.png)
Hope you'll fix it)

**Comment by Cigan12** [comment]
![image](https://user-images.githubusercontent.com/42859813/96576297-2ebb0880-12fc-11eb-84b3-9ac07bcea9fa.png)
![image](https://user-images.githubusercontent.com/42859813/96576337-3e3a5180-12fc-11eb-8ffd-83210ac9f2b2.png)

**Comment by avishain** [comment]
Thanks for raising this but I'm quite sure it has noting to do with the package.
In case it still appears after (1) clearing the cache and (2) restarting your computer - then please let me know and i'll try to figure it out.
I'm keeping the issue open and witing for your feedback.

**Comment by Cigan12** [comment]
Thanks for reply, i did that, but nothing changed, i take the RangeSlider component from the module and paste it in my project, and then it works, maybe i should do some specific with expo?

**Comment by avishain** [comment]
I assume then that it has something to do with my configurations.
What if you remove the app.json file. Does it make a difference?

**Comment by Cigan12** [comment]
> I assume then that it has something to do with my configurations.
> What if you remove the app.json file. Does it make a difference?

No, nothing changed(

**Comment by Cigan12** [comment]
Should i do expo eject?

**Comment by avishain** [comment]
No no. Do not eject just because of the Silder.
Keep using the managed workflow and just take the RangeSlider component from the module and paste it in your project ,

**Comment by Cigan12** [comment]
Okey, thank you, let me know, if something change

**Comment by avishain** [comment]
Closing issue as it isn't repetitive problem
