### ISSUE TITLE
Invalid Hook call when installing on Expo SDK39

### ISSUE THREAD

**Issue by nsbingham** [D10S60948/react-native-range-slider-expo#9]
I'm getting the following error when attempting to use the RangeSlider.

```
Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (react.development.js:1590)
    at useState (react.development.js:1618)
    at RangeSlider.tsx:47
```

I'm using the example code in the README.md.

```
<RangeSlider
    min={5}
    max={25}
    fromValueOnChange={(value) => setFromValue(value)}
    toValueOnChange={(value) => setToValue(value)}
    initialFromValue={11}
/>
<Text>from value: {fromValue}</Text>
<Text>to value: {toValue}</Text>
```

Thanks for any help!

**Comment by BobTape** [comment]
Hi, same issue, when i try this component.

**Comment by avishain** [comment]
Can you please show me (paste here) lines 40-50 of RangeSlider.tsx? you can find it in VScode by pressing F12 while standing on the imported component:
![image](https://user-images.githubusercontent.com/37651196/97899062-73559380-1d41-11eb-9012-eb37d2e0aaa8.png)

**Comment by pqthinh** [comment]
hello, I also have the same issue
RangeSlider.tsx 
![image](https://user-images.githubusercontent.com/50290559/98068900-01d82b00-1e90-11eb-8aa4-2c6e1dff3e21.png)

**Comment by avishain** [comment]
I fixed the problem. 
Please try to reinstall the package and let me know if it was solved for you.

**Comment by avishain** [comment]
Hi, was the problem solved after reinstalling?

**Comment by Osmanyteam** [comment]
Hey, i had the same problem but after reinstalling it works.

**Comment by avishain** [comment]
Glad to hear. Thanks for the update.
